swiftmailer:
     url: '%env(MAILER_URL)%'
     # transport: "%mailer_transport%"
     # host: "%mailer_host%"
     # port: "%mailer_port%"
     # username: "%mailer_user%"
     # password: "%mailer_password%"
     spool: { type: memory }
